apiVersion: batch/v1
kind: CronJob
metadata:
  name: backupjob-db
  namespace: {{ .Values.meshwiki_app_namespace }}
spec:
  schedule: {{ .Values.bookstack.backup.cron_schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backupjob-db
              image: "{{ .Values.db_image.repository }}:{{ .Values.db_image.tag }}"
              imagePullPolicy: {{ .Values.db_image.pullPolicy }}
              command:
                - /bin/bash
                - /backup.db.sh
              volumeMounts:
                - name: backup-script
                  mountPath: /backup.db.sh
                  subPath: backup.db.sh
                  readOnly: true
              env:
                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: wikiconfig
                      key: DB_HOST
                - name: DB_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: wikiconfig
                      key: DB_DATABASE
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: db-username
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: db-password
                - name: BACKUP_S3_URL
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: backup-s3-url
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: access-key-id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: secret-access-key
                - name: APP_URL
                  valueFrom:
                    configMapKeyRef:
                      name: wikiconfig
                      key: APP_URL
          volumes:
            - name: backup-script
              configMap:
                name: backup-script
                items:
                  - key: backup.db.sh
                    path: backup.db.sh
