apiVersion: batch/v1
kind: CronJob
metadata:
  name: backupjob-files
  namespace: {{ .Values.meshwiki_app_namespace }}
spec:
  schedule: {{ .Values.bookstack.backup.cron_schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backupjob-files
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /bin/bash
                - /backup.files.sh
              volumeMounts:
                - name: backup-script
                  mountPath: /backup.files.sh
                  subPath: backup.files.sh
                  readOnly: true
              env:
                - name: BACKUP_S3_URL
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: backup-s3-url
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: access-key-id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wiki-secrets
                      key: secret-access-key
          volumes:
            - name: backup-script
              configMap:
                name: backup-script
                items:
                  - key: backup.files.sh
                    path: backup.files.sh
