apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script
  namespace: {{ .Values.meshwiki_app_namespace }}
data:
  backup.db.sh: |
    if [ "$APP_URL" != "https://wiki.nycmesh.net" ]; then echo "Skip on $APP_URL"; exit 0; fi
    echo "Dumping db"
    mariadb-dump --skip-ssl -h "$DB_HOST" -u "$DB_USER" --password="$DB_PASS" "$DB_DATABASE" > wiki.sql
    echo "Creating tarball"
    backup_name="wiki_backup_db_$(date +%s).tar.gz"
    tar -chzvf $backup_name wiki.sql
    echo "push to s3"
    apk update
    apk add aws-cli
    aws s3 cp ./$backup_name "$BACKUP_S3_URL"
    echo "uploaded"
    rm $backup_name
    rm wiki.sql
    echo "done"
  backup.files.sh: |
    if [ "$APP_URL" != "https://wiki.nycmesh.net" ]; then echo "Skip on $APP_URL"; exit 0; fi
    echo "Creating tarball"
    cd /config
    backup_name="wiki_backup_files_$(date +%s).tar.gz"
    tar -chzvf $backup_name /app/www/public/uploads/ /app/www/storage/uploads/ /app/www/public/img/
    echo "push to s3"
    aws s3 cp ./$backup_name "$BACKUP_S3_URL"
    echo "uploaded"
    rm $backup_name
    echo "done"
  backup.entrypoint.sh: |
    echo "Startup"
    apk update
    apk add aws-cli
    mkdir -p /app/www/storage/uploads/
    ln -s /config/www/files /app/www/storage/uploads/files
    ln -s /config/www/images /app/www/storage/uploads/images
    ln -s /config/www/uploads /app/www/public/uploads
    echo "#!/bin/sh" > /etc/periodic/daily/backup
    echo "sh /backup.files.sh" >> /etc/periodic/daily/backup
    chmod +x /etc/periodic/daily/backup
    echo "Starting crond"
    crond -f
    echo "Error: Cron exited"
  restore.db.sh: |
    echo "Checking if restore is needed"
    echo "Restore file is: $RESTORE_S3_URL"
    if [ ! -z "$RESTORE_S3_URL" ]; then
      echo "Restoring from $RESTORE_S3_URL"
      apk update
      apk add aws-cli
      aws s3 cp "$RESTORE_S3_URL" /tmp/restore.tgz
      echo "downloaded tarball"
      tar -xzf /tmp/restore.tgz -C /
      mariadb -h "$DB_HOST" -u "$DB_USER" --password="$DB_PASS" $DB_DATABASE < /wiki.sql
    else
      echo "Not restoring"
    fi
    echo "done"
  restore.files.sh: |
    echo "Checking if restore is needed"
    echo "Restore file is: $RESTORE_S3_URL"
    if [ ! -z "$RESTORE_S3_URL" ]; then
      echo "Restoring from $RESTORE_S3_URL"
      apk update
      apk add aws-cli
      aws s3 cp "$RESTORE_S3_URL" /tmp/restore.tgz
      echo "downloaded tarball"
      tar -xzf /tmp/restore.tgz -C /
    else
      echo "Not restoring"
    fi
    echo "done"
