apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.bookstack.config_pvc_name }}
  namespace: {{ .Values.meshwiki_app_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.bookstack.config_pvc_size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.bookstack.image_pvc_name }}
  namespace: {{ .Values.meshwiki_app_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.bookstack.image_pvc_size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.bookstack.db.pvc_name }}
  namespace: {{ .Values.meshwiki_app_namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.bookstack.db.pvc_size }}