apiVersion: v1
kind: Secret
metadata:
  name: wiki-secrets
  namespace: {{ .Values.meshwiki_app_namespace }}
type: Opaque
data:
  db-username: {{ .Values.bookstack.db.username | b64enc | quote }}
  db-password: {{ .Values.bookstack.db.password | b64enc | quote }}
  db-root-password: {{ .Values.bookstack.db.root_password | b64enc | quote }}
  mail-username: {{ .Values.bookstack.mail.username | b64enc | quote }}
  mail-password: {{ .Values.bookstack.mail.password | b64enc | quote }}
  access-key-id: {{ .Values.bookstack.aws.access_key_id | b64enc | quote }}
  secret-access-key: {{ .Values.bookstack.aws.secret_access_key | b64enc | quote }}
  backup-s3-url: {{ .Values.bookstack.aws.backup_s3_url | b64enc | quote }}
  restore-s3-url: {{ .Values.bookstack.aws.restore_s3_url | b64enc | quote }}