apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstack-helm.fullname" . }}-bookstack
  namespace: {{ .Values.meshwiki_app_namespace }}
  labels:
    {{- include "bookstack-helm.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.bookstack.port }}
      targetPort: {{ .Values.bookstack.port }}
      protocol: TCP
      name: http
      nodePort: 30875
  selector:
    {{- include "bookstack-helm.selectorLabels" . | nindent 4 }}-bookstack
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstack-helm.fullname" . }}-db
  namespace: {{ .Values.meshwiki_app_namespace }}
  labels:
    {{- include "bookstack-helm.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.bookstack.db.port }}
      targetPort: {{ .Values.bookstack.db.port }}
      protocol: TCP
      name: db
  selector:
    {{- include "bookstack-helm.selectorLabels" . | nindent 4 }}-db