name: Deploy

on:
  push:
    branches: [ master, james/test ]

permissions: read-all

jobs:
  deploy_to_dev3:
      name: Deploy to dev3
      environment: dev3
      runs-on: ubuntu-latest
      #if: github.ref == 'refs/heads/master'
      steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4 # v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519 # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      
      - name: Setup WireGuard
        run:  |
          sudo apt install wireguard
          echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
          sudo ip link add dev wg1 type wireguard
          sudo ip address add dev wg1 ${{ secrets.WIREGUARD_OVERLAY_NETWORK_IP }} peer ${{ secrets.SSH_TARGET_IP }}
          sudo wg set wg1 listen-port 48123 private-key privatekey peer ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }} allowed-ips 0.0.0.0/0 endpoint ${{ secrets.WIREGUARD_ENDPOINT }}
          sudo ip link set up dev wg1

      - name: Install Helm Chart
        run: |
          scp ${{ secrets.SSH_USER }}@${{ secrets.SSH_TARGET_IP }}:~/.kube/config ~/.kube/config
          helm install \
            --kube-apiserver ${{ secrets.SSH_TARGET_IP }}:6443 \
            -n ${{ vars.APP_NAMESPACE }} \
            --create-namespace \
            wiki \
            bookstack-helm
            -f ./bookstack-helm/values.yaml \
            --set bookstack.db.username=\"${{ secrets.DB_USERNAME }}\" \
            --set bookstack.db.password=\"${{ secrets.DB_PASSWORD }}\" \
            --set bookstack.db.root_password=\"${{ secrets.ROOT_PASSWORD }}\" \
            --set bookstack.mail.username=\"${{ secrets.MAIL_USERNAME }}\" \
            --set bookstack.mail.password=\"${{ secrets.MAIL_PASSWORD }}\"

  deploy_to_prod1:
      name: Deploy to prod 1
      environment: prod1
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@d4fffb50872869abe2d9a9098a6d9c5aa7d16be4 # v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519 # optional
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      
      - name: Setup WireGuard
        run:  |
          sudo apt install wireguard
          echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
          sudo ip link add dev wg2 type wireguard
          sudo ip address add dev wg2 ${{ secrets.WIREGUARD_OVERLAY_NETWORK_IP }} peer ${{ secrets.SSH_TARGET_IP }}
          sudo wg set wg2 listen-port 48123 private-key privatekey peer ${{ secrets.WIREGUARD_PEER_PUBLIC_KEY }} allowed-ips 0.0.0.0/0 endpoint ${{ secrets.WIREGUARD_ENDPOINT }}
          sudo ip link set up dev wg2

      - name: Install Helm Chart
        run: |
          scp ${{ secrets.SSH_USER }}@${{ secrets.SSH_TARGET_IP }}:~/.kube/config ~/.kube/config
          helm install \
            --kube-apiserver ${{ secrets.SSH_TARGET_IP }}:6443 \
            -n ${{ vars.APP_NAMESPACE }} \
            --create-namespace \
            wiki \
            bookstack-helm
            -f ./bookstack-helm/values.yaml \
            --set bookstack.db.username=\"${{ secrets.DB_USERNAME }}\" \
            --set bookstack.db.password=\"${{ secrets.DB_PASSWORD }}\" \
            --set bookstack.db.root_password=\"${{ secrets.ROOT_PASSWORD }}\" \
            --set bookstack.mail.username=\"${{ secrets.MAIL_USERNAME }}\" \
            --set bookstack.mail.password=\"${{ secrets.MAIL_PASSWORD }}\"
